FROM alpine:3.20 AS capsetter
RUN apk add --no-cache libcap
COPY dist/rootfs/ /tmp/rootfs
RUN setcap cap_net_raw+ep /tmp/rootfs/usr/bin/mtr-packet

FROM scratch

WORKDIR /app
COPY dist/netwatch /app/netwatch
COPY dist/netwatch-proxy /app/netwatch-proxy
COPY dist/web /app/web
COPY dist/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=capsetter /tmp/rootfs/ /

ENV PATH=/usr/bin:/bin
EXPOSE 23087
CMD ["/app/netwatch"]
