// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type hostlimitAppConfig struct {
	_                      structs.HostLayout
	Generation             uint64
	DownloadBytesPerSecond uint64
	DownloadBurstBytes     uint64
	UploadMark             uint32
	MarkMask               uint32
}

type hostlimitDownloadState struct {
	_    structs.HostLayout
	Lock struct {
		_   structs.HostLayout
		Val uint32
	}
	Reserved       uint32
	Generation     uint64
	TokenNanobytes uint64
	LastRefillNs   uint64
}

type hostlimitFlowKey struct {
	_             structs.HostLayout
	LocalAddress  [16]uint8
	RemoteAddress [16]uint8
	LocalPort     uint16
	RemotePort    uint16
	Family        uint8
	Protocol      uint8
	Padding       [2]uint8
}

// loadHostlimit returns the embedded CollectionSpec for hostlimit.
func loadHostlimit() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HostlimitBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load hostlimit: %w", err)
	}

	return spec, err
}

// loadHostlimitObjects loads hostlimit and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*hostlimitObjects
//	*hostlimitPrograms
//	*hostlimitMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHostlimitObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHostlimit()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// hostlimitSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostlimitSpecs struct {
	hostlimitProgramSpecs
	hostlimitMapSpecs
	hostlimitVariableSpecs
}

// hostlimitProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostlimitProgramSpecs struct {
	HostlimitTagSocket *ebpf.ProgramSpec `ebpf:"hostlimit_tag_socket"`
	HostlimitTcEgress  *ebpf.ProgramSpec `ebpf:"hostlimit_tc_egress"`
	HostlimitTcIngress *ebpf.ProgramSpec `ebpf:"hostlimit_tc_ingress"`
}

// hostlimitMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostlimitMapSpecs struct {
	BridgeIfindexes  *ebpf.MapSpec `ebpf:"bridge_ifindexes"`
	Config           *ebpf.MapSpec `ebpf:"config"`
	DownloadStates   *ebpf.MapSpec `ebpf:"download_states"`
	Flows            *ebpf.MapSpec `ebpf:"flows"`
	LocalUploadBytes *ebpf.MapSpec `ebpf:"local_upload_bytes"`
	SocketTags       *ebpf.MapSpec `ebpf:"socket_tags"`
}

// hostlimitVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostlimitVariableSpecs struct {
}

// hostlimitObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHostlimitObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostlimitObjects struct {
	hostlimitPrograms
	hostlimitMaps
	hostlimitVariables
}

func (o *hostlimitObjects) Close() error {
	return _HostlimitClose(
		&o.hostlimitPrograms,
		&o.hostlimitMaps,
	)
}

// hostlimitMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHostlimitObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostlimitMaps struct {
	BridgeIfindexes  *ebpf.Map `ebpf:"bridge_ifindexes"`
	Config           *ebpf.Map `ebpf:"config"`
	DownloadStates   *ebpf.Map `ebpf:"download_states"`
	Flows            *ebpf.Map `ebpf:"flows"`
	LocalUploadBytes *ebpf.Map `ebpf:"local_upload_bytes"`
	SocketTags       *ebpf.Map `ebpf:"socket_tags"`
}

func (m *hostlimitMaps) Close() error {
	return _HostlimitClose(
		m.BridgeIfindexes,
		m.Config,
		m.DownloadStates,
		m.Flows,
		m.LocalUploadBytes,
		m.SocketTags,
	)
}

// hostlimitVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadHostlimitObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostlimitVariables struct {
}

// hostlimitPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHostlimitObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostlimitPrograms struct {
	HostlimitTagSocket *ebpf.Program `ebpf:"hostlimit_tag_socket"`
	HostlimitTcEgress  *ebpf.Program `ebpf:"hostlimit_tc_egress"`
	HostlimitTcIngress *ebpf.Program `ebpf:"hostlimit_tc_ingress"`
}

func (p *hostlimitPrograms) Close() error {
	return _HostlimitClose(
		p.HostlimitTagSocket,
		p.HostlimitTcEgress,
		p.HostlimitTcIngress,
	)
}

func _HostlimitClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed hostlimit_bpfel.o
var _HostlimitBytes []byte
