// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type hostlimitLimitPolicy struct {
	_                      structs.HostLayout
	Generation             uint64
	UploadBytesPerSecond   uint64
	UploadBurstBytes       uint64
	DownloadBytesPerSecond uint64
	DownloadBurstBytes     uint64
	Flags                  uint32
	Reserved               uint32
}

type hostlimitLimitState struct {
	_    structs.HostLayout
	Lock struct {
		_   structs.HostLayout
		Val uint32
	}
	Reserved       uint32
	Generation     uint64
	TokenNanobytes uint64
	LastRefillNs   uint64
	PassedBytes    uint64
	PassedPackets  uint64
	DroppedBytes   uint64
	DroppedPackets uint64
}

// loadHostlimit returns the embedded CollectionSpec for hostlimit.
func loadHostlimit() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HostlimitBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load hostlimit: %w", err)
	}

	return spec, err
}

// loadHostlimitObjects loads hostlimit and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*hostlimitObjects
//	*hostlimitPrograms
//	*hostlimitMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHostlimitObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHostlimit()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// hostlimitSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostlimitSpecs struct {
	hostlimitProgramSpecs
	hostlimitMapSpecs
	hostlimitVariableSpecs
}

// hostlimitProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostlimitProgramSpecs struct {
	HostlimitEgress  *ebpf.ProgramSpec `ebpf:"hostlimit_egress"`
	HostlimitIngress *ebpf.ProgramSpec `ebpf:"hostlimit_ingress"`
}

// hostlimitMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostlimitMapSpecs struct {
	DownloadStates *ebpf.MapSpec `ebpf:"download_states"`
	Policies       *ebpf.MapSpec `ebpf:"policies"`
	UploadStates   *ebpf.MapSpec `ebpf:"upload_states"`
}

// hostlimitVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hostlimitVariableSpecs struct {
}

// hostlimitObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHostlimitObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostlimitObjects struct {
	hostlimitPrograms
	hostlimitMaps
	hostlimitVariables
}

func (o *hostlimitObjects) Close() error {
	return _HostlimitClose(
		&o.hostlimitPrograms,
		&o.hostlimitMaps,
	)
}

// hostlimitMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHostlimitObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostlimitMaps struct {
	DownloadStates *ebpf.Map `ebpf:"download_states"`
	Policies       *ebpf.Map `ebpf:"policies"`
	UploadStates   *ebpf.Map `ebpf:"upload_states"`
}

func (m *hostlimitMaps) Close() error {
	return _HostlimitClose(
		m.DownloadStates,
		m.Policies,
		m.UploadStates,
	)
}

// hostlimitVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadHostlimitObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostlimitVariables struct {
}

// hostlimitPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHostlimitObjects or ebpf.CollectionSpec.LoadAndAssign.
type hostlimitPrograms struct {
	HostlimitEgress  *ebpf.Program `ebpf:"hostlimit_egress"`
	HostlimitIngress *ebpf.Program `ebpf:"hostlimit_ingress"`
}

func (p *hostlimitPrograms) Close() error {
	return _HostlimitClose(
		p.HostlimitEgress,
		p.HostlimitIngress,
	)
}

func _HostlimitClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed hostlimit_bpfel.o
var _HostlimitBytes []byte
